name: symfood
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip=22.1.2
  - pip:
      - absl-py==2.2.2
      - addict==2.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - autoflake==2.3.1
      - black==24.8.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - detectron2==0.6
      - detrex==0.3.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - eval_type_backport==0.2.2
      - exceptiongroup==1.2.2
      - fairscale==0.4.13
      - filelock==3.16.1
      - flake8==7.1.2
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - GitPython==3.1.44
      - google-auth==2.39.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - huggingface-hub==0.30.2
      - hydra-core==1.3.2
      - idna==3.10
      - importlib_metadata==8.5.0
      - importlib_resources==6.4.5
      - iniconfig==2.1.0
      - iopath==0.1.9
      - isort==5.13.2
      - kiwisolver==1.4.7
      - Markdown==3.7
      - markdown-it-py==3.0.0
      - MarkupSafe==2.1.5
      - matplotlib==3.7.5
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmengine==0.10.7
      - mypy_extensions==1.1.0
      - numpy==1.24.4
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pathspec==0.12.1
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - portalocker==3.0.0
      - protobuf==5.29.4
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1_modules==0.4.2
      - pybind11==2.13.6
      - pycocotools==2.0.7
      - pycodestyle==2.12.1
      - pydantic==2.10.6
      - pydantic_core==2.27.2
      - pyflakes==3.2.0
      - Pygments==2.19.1
      - pyparsing==3.1.4
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - PyYAML==6.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scipy==1.10.1
      - sentry-sdk==2.27.0
      - setproctitle==1.3.5
      - shapely==2.0.7
      - six==1.17.0
      - smmap==5.0.2
      - submitit==1.5.2
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - thop==0.1.1.post2209072238
      - timm==1.0.15
      - tomli==2.2.1
      - torch==1.12.1+cu113
      - torchaudio==0.12.1+cu113
      - torchvision==0.13.1+cu113
      - tqdm==4.67.1
      - typing_extensions==4.13.2
      - urllib3==2.2.3
      - wandb==0.19.10
      - Werkzeug==3.0.6
      - wheel==0.45.1
      - yacs==0.1.8
      - yapf==0.43.0
      - zipp==3.20.2

